name: Cluster IT - 1C1D1A

on:
  push:
    branches:
      - master
      - 'rel/*'
      - 'rc/*'
    paths-ignore:
      - 'docs/**'
      - 'site/**'
  pull_request:
    branches:
      - master
      - 'rel/*'
      - 'rc/*'
      - 'force_ci/**'
    paths-ignore:
      - 'docs/**'
      - 'site/**'
  # allow manually run the action:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3
  MAVEN_ARGS: --batch-mode --no-transfer-progress
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

jobs:
  AINode:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ ubuntu-latest ]
    runs-on: [self-hosted, gpu]

    steps:
      - uses: actions/checkout@v4
      - name: IT Test
        shell: bash
        run: |
          mvn clean verify \
          -P with-integration-tests,with-ainode \
          -DskipUTs \
          -DintegrationTest.forkCount=1 \
          -pl integration-test,iotdb-core/ainode \
          -am \
          -PAIClusterIT
      - name: Upload Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cluster-log-ainode-${{ matrix.os }}
          path: integration-test/target/*-logs
          retention-days: 30
