# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: 
      - master
      - 'rel/*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: 
      - master
      - 'rel/*'
      - cluster_new
    paths-ignore:
      - 'docs/**'
        
jobs:
   build:
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        java: [8, 11.0.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os}}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Check Apache Rat
      run: mvn -B apache-rat:check
    - name: Set Hadoop PATH
      run: echo "/d/a/iotdb/target/hadoop/bin" >> $GITHUB_PATH
    - name: Download Hadoop Tools if Needed
      if: matrix.os == 'windows-latest'
      env:
        HADOOP_HOME: /c/hadoop
      # Using Powershell ...
      # github action put codes to d:\a
      run: mkdir D:\a\iotdb\target\hadoop\bin ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/winutils.exe -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hadoop.dll -OutFile C:\windows\system32  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hadoop -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hadoop.cmd -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hadoop.exp -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hadoop.lib -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hadoop.pdb -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hdfs.dll -OutFile C:\windows\system32  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hdfs -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hdfs.cmd -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hdfs.exp -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hdfs.lib -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hdfs.pdb -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/hdfs_static.lib -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/libwinutils.lib -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/mapred -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/mapred.cmd -OutFile D:\a\iotdb\target\hadoop\bin  ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/rcc -OutFile D:\a\iotdb\target\hadoop\bin ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/winutils.pdb -OutFile D:\a\iotdb\target\hadoop\bin ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/yarn -OutFile D:\a\iotdb\target\hadoop\bin ; `
           Invoke-WebRequest https://github.com/cdarlint/winutils/raw/master/hadoop-2.7.3/bin/yarn.cmd -OutFile D:\a\iotdb\target\hadoop\bin
    - name: Check Hadoop Path
      shell: bash
      run: echo $PATH
    - name: Test with Maven
      shell: bash
      run: mvn -B clean test integration-test -Dtest.port.closed=true 
