# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Sonar And Coverall with Maven

on:
  push:
    branches: 
      - master
      - 'rel/*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: 
      - master
      - 'rel/*'
      - cluster_new
    paths-ignore:
      - 'docs/**'

jobs:
  sonar:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.x
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: sonar-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: SonarCloud Test
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: '2d9c9a58d772a57806a168e00181e3e19f2763dc'
        run: |
          mvn -B verify sonar:sonar \
          -Dsonar.organization=apache \
          -Dsonar.projectKey=apache_incubator-iotdb \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }} \
          -DskipTests -pl '!distribution' -am
  
  coveralls:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: code-coverage-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Integration Test
        run: mvn -B post-integration-test -Pcode-coverage -Pcoveralls -pl '!distribution' -am
      - name: Code Coverage (Coveralls) Test
        run: |
          mvn -B coveralls:report \
          --no-transfer-progress \
          -DserviceName=travis_ci \
          -D branch=$BRANCH_NAME \
          -D pullRequest=$PR_NUMBER \
          -D repoToken=MiEOlMMMNQhLNV4yayn7rRUPyVSQzbzbZ \
          -pl tsfile,server,jdbc,cli,session,hive-connector,flink-iotdb-connector,flink-tsfile-connector
