# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Sonar-Coveralls

on:
  workflow_run:
    workflows: ["Run Tests for Sonar-Coveralls"]

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Code Coverage (Coveralls)
        run: |
          mvn -B post-integration-test -Pcode-coverage -pl code-coverage
          mvn -B coveralls:report \
          -DserviceName=travis_ci \
          -Dbranch=$BRANCH_NAME \
          -DpullRequest=$PR_NUMBER \
          -DrepoToken=${{ secrets.COVERALL_TOKEN }} \
          -Pcode-coverage
      - name: SonarCloud Report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          mvn -B verify sonar:sonar \
          -Dsonar.organization=apache \
          -Dsonar.projectKey=apache_incubator-iotdb \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }} \
          -DskipTests -pl '!distribution' -am
